name: Deploy Homolog
on:
  push:
    branches:
      - homolog
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: 'npm i && npm run build --configuration=homolog'
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VENDOR_PLANOS }}'
          channelId: live
          projectId: vendor-planos
          target: hml-vendor-planos
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
